apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: billing-postgresql
  labels:
    app: billing-postgresql
spec:
  selector:
    matchLabels:
      app: billing-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-postgresql
    spec:
      containers:
      - name: billing-postgresql
        image: postgres:13.0-alpine
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
